initial commit

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -7,14 +7,24 @@ source "$(dirname "$0")/../lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+case "$OSTYPE" in
+  darwin*) release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-macos.zip" ;;
+  linux*) release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-linux64.tar.gz" ;;
+  *) fail "Unsupported platform" ;;
+esac
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+if [[ $release_file == *.tar.gz ]]; then
+    #  Extract contents of tar.gz file into the download directory
+    tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+elif [[ $release_file == *.zip ]]; then
+    #  Extract contents of zip file into the download directory
+    unzip -j "$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+else
+    fail "Unsupported file type"
+fi
 
-# Remove the tar.gz file since we don't need to keep it
+# Remove the download file since we don't need to keep it
 rm "$release_file"
